//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "music_tracks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub album_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    pub track_number: Option<i32>,
    pub disc_number: Option<i32>,
    pub duration: Option<i32>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub mb_track_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub lyrics_path: Option<String>,
    pub bitrate: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub codec: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub genre: Option<String>,
    pub sample_rate: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::media_files::Entity")]
    MediaFiles,
    #[sea_orm(
        belongs_to = "super::music_albums::Entity",
        from = "Column::AlbumId",
        to = "super::music_albums::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    MusicAlbums,
}

impl Related<super::media_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaFiles.def()
    }
}

impl Related<super::music_albums::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MusicAlbums.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
